# Welcome to Jekyll!
# rebuild test
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DSC 80
description: DSC 80, Summer 2026 at UC San Diego
tagline: Practice and Application of Data Science
baseurl: '/dsc80-2026-su' 
url: 'https://dsc-courses.github.io' 
author: DSC 80 course staff
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]


# reference these in the site using site.urls, e.g.:
#
# Check out our [Campuswire discussion forum]({{ site.urls.campuswire }}) for
# questions and announcements.
urls:
  campuswirejoin: &campuswirejoin 'https://campuswire.com/p/G65427605'
  campuswire: &campuswire 'https://campuswire.com/c/G65427605' 
  gradescope: &gradescope 'https://www.gradescope.com/courses/1288255'
  reference: &reference 'https://dsc-courses.github.io/bpd-reference/docs/documentation/intro'
  practice: &practice 'https://practice.dsc10.com/'
  cc: &cc 'http://cc.dsc10.com/'
  podcasts: &podcasts 'https://podcast.ucsd.edu/'
  syllabuscheck: &syllabuscheck 'https://docs.google.com/forms/d/e/1FAIpQLScOVK4Q8Xe9T0xQ4RQBB2ZAkySvnWHDCQK_k_33nhw0zDvkSQ/viewform?usp=dialog'
  welcome: &welcome 'https://forms.gle/HE1a1V7rvu5BCuSZ7'
  github: &github 'https://github.com/dsc-courses/dsc10-2026-sp'
  pretest: &pretest 'https://practice.dsc10.com/pretest/'
  classroom: &classroom 'https://map.concept3d.com/?id=1005#!m/761769?share'

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.12.0
color_scheme: bluecsd
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  💻 GitHub:
    - *github
  🙋 Campuswire:
    - *campuswire
  💯 Gradescope:
    - *gradescope
  💪 Practice:
    - *practice
footer_content:

# Collections for website data
collections:
  staffers:
  staffersnobio:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/images/'
  - scope:
      path: ''
      type: staffersnobio
    values:
      layout: staffer_no_bio
      subpath: '/assets/images/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag

# callouts
callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important Announcement
    color: red
  note:
    title: Note
    color: yellow
  success:
    title: ""
    color: green
